Broken:
  combat:
    SPAWNER: 5000
  mining:
    SAND: 3
    NETHERRACK: 3
    GRAVEL: 3
    STONE: 5
    COBBLESTONE: 5
    DIORITE: 5
    ANDESITE: 5
    GRANITE: 5
    DEEPSLATE: 6
    CALCITE: 8
    TUFF: 7
    OBSIDIAN: 10
    COBBLED_DEEPSLATE: 6
    IRON_ORE: 68
    DEEPSLATE_IRON_ORE: 68
    COAL_ORE: 47
    DEEPSLATE_COAL_ORE: 47
    GOLD_ORE: 475
    DEEPSLATE_GOLD_ORE: 475
    LAPIS_ORE: 350
    DEEPSLATE_LAPIS_ORE: 350
    REDSTONE_ORE: 360
    DEEPSLATE_REDSTONE_ORE: 360
    COPPER_ORE: 20
    DEEPSLATE_COPPER_ORE: 20
    DIAMOND_ORE: 2100
    DEEPSLATE_DIAMOND_ORE: 2100
    EMERALD_ORE: 5000
    DEEPSLATE_EMERALD_ORE: 5000
    ANCIENT_DEBRIS: 3000
    NETHER_QUARTZ_ORE: 70
    NETHER_GOLD_ORE: 37
    GLOWSTONE: 77
    AMETHYST_BLOCK: 13
    AMETHYST_SHARD: 333
  forage:
    ACACIA_LEAVES: 4
    BIRCH_LEAVES: 4
    DARK_OAK_LEAVES: 4
    OAK_LEAVES: 4
    SPRUCE_LEAVES: 4
    JUNGLE_LEAVES: 4
    AZALEA_LEAVES: 4
    FLOWERING_AZALEA_LEAVES: 4
    ACACIA_LOG: 128
    JUNGLE_LOG: 128
    OAK_LOG: 128
    DARK_OAK_LOG: 128
    SPRUCE_LOG: 128
    BIRCH_LOG: 128
    CRIMSON_STEM: 128
    WARPED_STEM: 128
  farming:
    PUMPKIN: 35
    MELON: 35
Killed:
  combat:
    PigZombie: 5
    Zombie: 150
    Skeleton: 175
    Creeper: 250
    Spider: 210
    CaveSpider: 225
    WitherSkeleton: 610
    Blaze: 590
    ZombieVillager: 150
    Zoglin: 660
    Phantom: 1450
    Hoglin: 700
    Piglin: 455
    PiglinBrute: 650
    Evoker: 600
    Vex: 405
    Drowned: 150
    Ghast: 1500
    Husk: 90
    Slime: 75
    MagmaCube: 75
    Ravager: 3300
    Wither: 9000
    EnderDragon: 10000
    Illusioner: 620
    Stray: 100
    Vindicator: 580
    Bat: 100
    Witch: 300
    Shulker: 577
    Silverfish: 152
    Guardian: 800
    ElderGuardian: 2700
    Pillager: 550
  fishing:
    Salmon: 80
    Cod: 70
    PufferFish: 120
    Squid: 100
    TropicalFish: 180