Broken:
  combat:
    SPAWNER: 5000
  mining:
    SAND: 3
    NETHERRACK: 3
    GRAVEL: 3
    STONE: 5
    COBBLESTONE: 5
    DIORITE: 5
    ANDESITE: 5
    GRANITE: 5
    DEEPSLATE: 6
    CALCITE: 8
    TUFF: 7
    OBSIDIAN: 10
    COBBLED_DEEPSLATE: 6
    IRON_ORE: 68
    DEEPSLATE_IRON_ORE: 68
    COAL_ORE: 47
    DEEPSLATE_COAL_ORE: 47
    GOLD_ORE: 475
    DEEPSLATE_GOLD_ORE: 475
    LAPIS_ORE: 350
    DEEPSLATE_LAPIS_ORE: 350
    REDSTONE_ORE: 360
    DEEPSLATE_REDSTONE_ORE: 360
    COPPER_ORE: 20
    DEEPSLATE_COPPER_ORE: 20
    DIAMOND_ORE: 2100
    DEEPSLATE_DIAMOND_ORE: 2100
    EMERALD_ORE: 5000
    DEEPSLATE_EMERALD_ORE: 5000
    ANCIENT_DEBRIS: 3000
    NETHER_QUARTZ_ORE: 70
    NETHER_GOLD_ORE: 37
    GLOWSTONE: 77
    AMETHYST_BLOCK: 13
    AMETHYST_SHARD: 333
  forage:
    ACACIA_LEAVES: 4
    BIRCH_LEAVES: 4
    DARK_OAK_LEAVES: 4
    OAK_LEAVES: 4
    SPRUCE_LEAVES: 4
    JUNGLE_LEAVES: 4
    AZALEA_LEAVES: 4
    CHERRY_LEAVES: 4
    FLOWERING_AZALEA_LEAVES: 4
    MANGROVE_LEAVES: 4
    ACACIA_LOG: 128
    JUNGLE_LOG: 128
    OAK_LOG: 128
    DARK_OAK_LOG: 128
    SPRUCE_LOG: 128
    CHERRY_LOG: 128
    BIRCH_LOG: 128
    MANGROVE_LOG: 128
    CRIMSON_STEM: 128
    WARPED_STEM: 128
    BAMBOO: 16
  farming:
    PUMPKIN: 35
    MELON: 35
    SUGAR_CANE: 30
    WHEAT: 110
    CARROTS: 78
    POTATOES: 78
    NETHER_WART: 85
Killed:
  combat:
    PigZombie: 5
    Zombie: 150
    Skeleton: 175
    Creeper: 250
    Spider: 210
    CaveSpider: 225
    WitherSkeleton: 610
    Blaze: 590
    ZombieVillager: 150
    Zoglin: 660
    Phantom: 1450
    Hoglin: 700
    Piglin: 455
    PiglinBrute: 650
    Evoker: 600
    Vex: 405
    Drowned: 150
    Ghast: 1500
    Husk: 90
    Slime: 75
    MagmaCube: 75
    Ravager: 3300
    Wither: 9000
    EnderDragon: 10000
    Illusioner: 620
    Stray: 100
    Vindicator: 580
    Bat: 100
    Witch: 300
    Shulker: 577
    Silverfish: 152
    Guardian: 800
    ElderGuardian: 2700
    Pillager: 550
  fishing:
    Salmon: 80
    Cod: 70
    PufferFish: 120
    Squid: 100
    TropicalFish: 180
Caught:
  FISH:
    COD:
      weight: 60
      reward: 300
      name: "대구"
    SALMON:
      weight: 85
      reward: 420
      name: "연어"
    PUFFERFISH:
      weight: 98
      reward: 900
      name: "복어"
    TROPICAL_FISH:
      weight: 100
      reward: 2160
      name: "열대어"
  COMMON:
    STICK:
      weight: 5
      reward: 145
      name: "막대기"
    LILY_PAD:
      weight: 22
      reward: 70
      name: "수련잎"
    BOWL:
      weight: 32
      reward: 120
      name: "그릇"
    LEATHER:
      weight: 42
      reward: 100
      name: "가죽"
    ROTTEN_FLESH:
      weight: 52
      reward: 30
      name: "썩은 살점"
    BONE:
      weight: 62
      reward: 40
      name: "뼈"
    GLASS_BOTTLE:
      weight: 72
      reward: 90
      name: "유리병"
    STRING:
      weight: 77
      reward: 20
      name: "실"
    INK_SAC:
      weight: 78
      reward: 350
      name: "먹물"
    TRIPWIRE_HOOK:
      weight: 88
      reward: 130
      name: "철사 덫 갈고리"
    LEATHER_BOOTS:
      weight: 98
      reward: 85
      name: "가죽 장화"
    FISHING_ROD:
      weight: 100
      reward: 105
      name: "낚싯대"
  RARE:
    WIND_CHARGE:
      weight: 16
      reward: 2222
      name: "돌풍구"
    NAME_TAG:
      weight: 26
      reward: 3400
      name: "이름표"
    NAUTILUS_SHELL:
      weight: 36
      reward: 3070
      name: "앵무조개 껍데기"
    SADDLE:
      weight: 46
      reward: 2600
      name: "안장"
    EXPERIENCE_BOTTLE:
      weight: 56
      reward: 2777
      name: "경험치 병"
    DIAMOND:
      weight: 66
      reward: 4000
      name: "다이아몬드"
    FISHING_ROD:
      weight: 76
      reward: 2800
      name: "마법이 부여된 낚싯대"
    GOLDEN_APPLE:
      weight: 86
      reward: 2840
      name: "황금 사과"
    BOW:
      weight: 96
      reward: 2920
      name: "마법이 부여된 활"
    SHULKER_SHELL:
      weight: 100
      reward: 4800
      name: "셜커 껍데기"
  EPIC:
    ANCIENT_DEBRIS:
      weight: 25
      reward: 15000
      name: "고대 잔해"
    TOTEM_OF_UNDYING:
      weight: 50
      reward: 15000
      name: "불사의 토템"
    EXPERIENCE_BOTTLE:
      weight: 60
      reward: 15000
      name: "1500 인첸트 경험치"
    WITHER_SKELETON_SKULL:
      weight: 80
      reward: 15000
      name: "위더 스켈레톤 해골"
    MUSIC_DISC_13:
      weight: 81
      reward: 15000
      name: "뮤직 디스크 - 13"
    MUSIC_DISC_BLOCKS:
      weight: 82
      reward: 15000
      name: "뮤직 디스크 - Blocks"
    MUSIC_DISC_CAT:
      weight: 83
      reward: 15000
      name: "뮤직 디스크 - Cat"
    MUSIC_DISC_CHIRP:
      weight: 84
      reward: 15000
      name: "뮤직 디스크 - Chirp"
    MUSIC_DISC_MALL:
      weight: 85
      reward: 15000
      name: "뮤직 디스크 - Mall"
    MUSIC_DISC_MELLOHI:
      weight: 86
      reward: 15000
      name: "뮤직 디스크 - Mellohi"
    MUSIC_DISC_PIGSTEP:
      weight: 87
      reward: 15000
      name: "뮤직 디스크 - Pigstep"
    MUSIC_DISC_FAR:
      weight: 88
      reward: 15000
      name: "뮤직 디스크 - Far"
    MUSIC_DISC_WAIT:
      weight: 89
      reward: 15000
      name: "뮤직 디스크 - Wait"
    MUSIC_DISC_WARD:
      weight: 90
      reward: 15000
      name: "뮤직 디스크 - Ward"
    MUSIC_DISC_STAL:
      weight: 91
      reward: 15000
      name: "뮤직 디스크 - Stal"
    MUSIC_DISC_STRAD:
      weight: 92
      reward: 15000
      name: "뮤직 디스크 - Strad"
    ENCHANTED_GOLDEN_APPLE:
      weight: 100
      reward: 15000
      name: "마법이 부여된 황금 사과"
  LEGENDARY:
    NETHERITE_INGOT:
      weight: 40
      reward: 75000
      name: "네더라이트 주괴"
    NETHERITE_PICKAXE:
      weight: 60
      reward: 75000
      name: "마법이 부여된 네더라이트 곡괭이"
    HEART_OF_THE_SEA:
      weight: 70
      reward: 75000
      name: "바다의 심장"
    BOW:
      weight: 75
      reward: 75000
      name: "무한 수선 활"
    NETHER_STAR:
      weight: 85
      reward: 75000
      name: "네더의 별"
    NETHERITE_HELMET:
      weight: 100
      reward: 75000
      name: "마법이 부여된 네더라이트 투구"
