name: TestPlugin
version: '2024.10'
authors: [jiwonpaeng, mmiimin]
main: com.paeng.testPlugin.TestPlugin
api-version: '1.20.6'
depend: [CoreProtect]
commands:
  menu:
    description: Calls up user profile (try /m)
    aliases: m
  profile:
    description: Calls up user profile